### ISSUE TITLE
[suggestion] showing the users' groups 

### ISSUE THREAD

**Issue by ibrahimk157** [ReFlar/user-management#10]
Would be really helpful if the extension would also show the users' group(s) beside their username in the user management dashboard

**Comment by Ralkage** [comment]
@CDK2020 do you still wan't to address this when I'm done splitting Strikes and User Management?

**Comment by HLFH** [comment]
It would be helpful to assign groups to the user such as the old https://github.com/flagrow/flarum-ext-guardian. @Ralkage

**Comment by Ralkage** [comment]
We are about to archive this extension as abandoned in favor of the planned merged extensions via Flagrow space. With that being said, we are no longer supporting this extension or providing any new bug fixes and or new features.

Please consider upgrading your Flarum version to support future development of newer and updated extensions :)
