### ISSUE TITLE
User Profile Customization

### ISSUE THREAD

**Issue by AngellitoX** [ReFlar/user-management#14]
1. Allow users to change their profile header background by letting them chose their preferred flat color or upload a cover image.

2. Possibly, change the way Male/Female is displayed, and instead use FontAwesome Icons that when hovered it shows a small popup of the "Male/Female" word.

**Comment by Ralkage** [comment]
Item 1 will be addressed in a separate extension/

Item 2 will be addressed in the extension code-named "Reggy" which is secretly a WIP.
