### ISSUE TITLE
ReflectionException

### ISSUE THREAD

**Issue by falseresync** [ReFlar/user-management#17]
PHP 7.1.12
Nginx 1.13.7
Flarum last
My stack trace:
`Fatal error: Uncaught ReflectionException: Class Reflar\UserManagement\Listeners\AddApiAttributes does not exist in /home/site/forum/vendor/illuminate/container/Container.php:741
Stack trace: 
#0 /home/site/forum/vendor/illuminate/container/Container.php(741): ReflectionClass->__construct('Reflar\\UserMana...') 
#1 /home/site/forum/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build('Reflar\\UserMana...', Array)
#2 /home/site/forum/vendor/flarum/core/src/Foundation/Application.php(514): Illuminate\Container\Container->make('Reflar\\UserMana...', Array)
#3 /home/site/forum/vendor/illuminate/events/Dispatcher.php(149): Flarum\Foundation\Application->make('Reflar\\UserMana...')
#4 /home/site/forum/vendor/illuminate/events/Dispatcher.php(135): Illuminate\Events\Dispatcher->resolveSubscriber('Reflar\\UserMana...')
#5 /home/site/forum/vendor/reflar/user-management/bootstrap.php(20): Illuminate\Events\Dispatcher->subscribe('Reflar\\UserMana...')
#6 [internal function]: Flarum\Extension\ExtensionSe in /home/site/forum/vendor/illuminate/container/Container.php on line 741`

**Comment by Ralkage** [comment]
Greetings and sorry for the late reply! Are you still having this issue?

**Comment by Ralkage** [comment]
User did not follow up, we will assume that this is no longer an issue.
