### ISSUE TITLE
Translation missing for english?

### ISSUE THREAD

**Issue by PHPVibe** [ReFlar/user-management#19]
From what I can tell the extension works fine. 
Just that some text translations are missing.
In both the admin menu and component page.

reflar-usermanagement.admin.page.about_text

> reflar-usermanagement.admin.modal.email_switch
> reflar-usermanagement.admin.modal.gender_label
> reflar-usermanagement.admin.modal.age_label
> reflar-usermanagement.admin.modal.recaptcha
> reflar-usermanagement.admin.modal.spam
> reflar-usermanagement.admin.modal.amount_label

Here is how the actual text is showing.

Hope this helps!

Kind regards,
Rafael

**Comment by Ralkage** [comment]
@PHPVibe try these options in any order:

1. Clear your browser cache (this typically fixes the locale issue)
2. Using SSH in the root directory of your Flarum installation, run the following command:
`php flarum cache:clear`

Refresh the page afterwards and let me know if either of those methods worked for you.
