### ISSUE TITLE
SignUpModal can't be extended by other extensions with user-management active

### ISSUE THREAD

**Issue by clarkwinkelmann** [ReFlar/user-management#20]
This extension overrides the prototype methods of SignUpModal, making it impossible to extend by any other extension. In particular this breaks compatibility with Flagrow Terms.

The faulty code is around here in the `main.js` file https://github.com/ReFlar/user-management/blob/31adac4bcb4783436b115642f364d0bfe46e18c1/js/forum/src/main.js#L85

If an extension like Flagrow Terms is loaded before User Management and extending the `init`, `body` or `onsubmit` methods the changes will be wiped out.

I suggest you use similar hacking to what I did in Terms https://github.com/flagrow/terms/blob/master/js/forum/src/addFieldsToRegister.js so you don't break extensibility for other extensions.

Of course once merged there will be a prettier way to do it in beta8 as already discussed on the forum https://github.com/flarum/core/pull/1420

I can submit a pull request if you want.

**Comment by Ralkage** [comment]
We're planning to remove the registration related features that's currently in this extension. A **Strikes** extension will handle the strikes portion and "Reggy" will handle the registration modal related plans we have once your fix as well as Flarum Beta 8 become available.

**Comment by Ralkage** [comment]
This removal will happen anytime between the end of this week and next week. We will release these breaking changes in User Management version 0.1.0.

**Comment by clarkwinkelmann** [comment]
So do we just say the extensions are incompatible for now ?

**Comment by Ralkage** [comment]
Yessir.

I'll update the User Management compser.json and add the following line until we can get this issue resolved:

```
"conflict": {
        "flagrow/terms": "^0.1.2"
```

or should I be using `*` instead of the latest version number and up just in case other users are using an older version?

**Comment by Ralkage** [comment]
I will also let the users know why these two extensions aren't compatible in this quick patch update via release description and Flarum discussion.

**Comment by Ralkage** [comment]
As discussed and as a temp fix, I will add the following to the composer.json file for this extension.

```
"conflict": {
        "flagrow/terms": ">=0.1.0"
```

**Comment by Ralkage** [comment]
@clarkwinkelmann this issue is being addressed with a temporary solution in our next patch release via #21.

**Comment by Kenner-G** [comment]
hey. fixed?

**Comment by Ralkage** [comment]
@Kenner-G this issue will be fixed in Beta 8, but by then, User Management will no longer have user registration tweaks or Strikes. Those will be their own extensions :)

**Comment by Padrio** [comment]
So, since 2018 nothing seems to happened here. Are there any new information on this? I really woul'd appreciate to use this plugin along with the terms.

**Comment by clarkwinkelmann** [comment]
Beta 8 includes the new registration extension options that won't create conflicts. Terms uses that since its beta 8 release, so no longer an issue on our side.

The question is more about if ReFlar plans to update this extension to beta 8

**Comment by Ralkage** [comment]
@Padrio this will not be updated for Beta 8, we are taking the route to which the combination of the planned merger of [`flagrow/user-directory`](https://github.com/flagrow/user-directory) and [`flagrow/users-list`](https://github.com/flagrow/users-list) (if that's still something that's happening ofc, @clarkwinkelmann ;) )

**Comment by clarkwinkelmann** [comment]
@Ralkage it is still planned and @luceos started working on it but I'm not sure who will finish it and when. User Directory received its own beta 8 update in the meantime.

Maybe worth to archive repo or close issues as won't fix in this situation ?

**Comment by Ralkage** [comment]
Thank you for verifying @clarkwinkelmann 👍 

To everyone else who stood by us and supported one of our very first successful extensions in ReFlar Land:

We are about to archive this extension as abandoned in favor of the planned merged extensions via Flagrow space. With that being said, we are no longer supporting this extension or providing any new bug fixes.

Please consider upgrading your Flarum version to support future development of newer and updated extensions :)
