### ISSUE TITLE
Error parsing YAML, invalid file "/vendor/reflar/user-management/src/Listeners/../../locale/en.yml"

### ISSUE THREAD

**Issue by HLFH** [ReFlar/user-management#23]
### Instructions (MUST READ FIRST)

Before we can address your issues and concerns with the behavior of our work, we require every bit of detail from you to the fullest extent of this form. If this form is not properly filled out to it's entirity, we, ReFlar, reserve the right to close your issue due to lack of information thereof as well as not following instructions.

* [x] By agreeing to these terms, you can simply leave this checkbox checked.

### Please Mentally Go Over the Following Items Before Filling Out this Form:

* Can you reproduce this problem in debug mode? Yes
* Are you running the latest version of this extension? Yes
* Is your Flarum up-to-date? Yes. Beta 8

### Description

When I enable this extension in beta 8, I got the error:
`Error parsing YAML, invalid file "/vendor/reflar/user-management/src/Listeners/../../locale/en.yml"`

### Steps to Reproduce

1. Update Flarum to beta 8
2. Do some modifications to make beta 8 work
3. Check the extensions that do not work
4. Enable reflar/user-management
5. Big issue shown above that makes Flarum stuck

**Expected Behavior:** 
user-management should work

**Actual Behavior:**
user-management breaks Flarum

## Technical Details

- Version of Flarum (x.y.z): beta 8, master
- Version of extension (x.y.z): master
- The webserver you are running (Apache, Nginx, etc): Nginx
- PHP version (x.y.z): 7.2.6
- Hosted environment (Shared, VPS, etc): Dedicated
- Hosting provider (https://some-amazing-provider.com): Online.net

## Flarum Info

```
Flarum core 0.1.0-beta.7
PHP 7.2.6
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, bcmath, Phar, curl, exif, ftp, gd, gettext, iconv, imap, intl, mysqli, pdo_mysql, pdo_sqlite, pspell, sockets, sqlite3, tidy, xmlrpc, zip, geoip, redis, Zend OPcache
EXT flarum-approval dev-master
EXT flarum-bbcode dev-master
EXT vingle-configure-smtp dev-master
EXT cbmainz-de dev-master
EXT flarum-emoji dev-master
EXT clarkwinkelmann-emojionearea dev-master
EXT flarum-english dev-master
EXT flagrow-byobu dev-master
EXT flagrow-split dev-master
EXT flarum-flags dev-master
EXT milescellar-french dev-master
EXT flarum-likes dev-master
EXT flarum-lock dev-master
EXT flarum-markdown dev-master
EXT xengine-markdown-editor dev-master
EXT flarum-mentions dev-master
EXT flarum-statistics dev-master
EXT flarum-sticky dev-master
EXT flarum-subscriptions dev-master
EXT flarum-suspend dev-master
EXT flarum-tags dev-master
EXT avatar4eg-transliterator dev-master
Base URL: https://forum.mydomain.com
Installation path: /srv/http/mydomain.com/forum
Debug mode ON
```

## Log Files

```
No relevant logs
```

**Comment by dsevillamartin** [comment]
This is not a bug with our extension, as it hasn't been made to work with beta 8. More things are going to break in beta 8 that haven't already broken.
You shouldn't be reporting errors for extensions in beta 8, or reporting errors with extensions in beta 8 at all. It's in development, errors are expected.

Furthermore, this extension is going to be split for beta 8 (https://discuss.flarum.org/d/5444-user-management-by-reflar/199).

**Comment by mattmalec** [comment]
Funny you should mention that, because I take a look at the `en.yml` file, and that line (57) does not have single quotation marks around it. Adding those quotations on your extension fixes the bug. Therefore, it is a bug with your extension. Furthermore, it doesn't even work.

**Comment by dsevillamartin** [comment]
@mjmalec It _is_ a bug with the extension. That was phrased incorrectly. But it should _not_ be used in beta 8, as it has not been updated to work with it. User Management is going to be split, refer to the post linked in my earlier comment for details.

**Comment by mattmalec** [comment]
I appreciate the swift response. What version of Flarum is compatible with User Management as having some sort of management for users is quite a critical thing to have.

**Comment by dsevillamartin** [comment]
The latest Flarum version that User Management is compatible with is beta 7.

**Comment by mattmalec** [comment]
Thank you! I will have to give that a try!
