### ISSUE TITLE
Split the extension

### ISSUE THREAD

**Issue by jtojnar** [ReFlar/user-management#7]
This extension is nice and integrated but some communities might only need a subset of the features. For this reason, I propose that the extension were split into following packages:

* User list
* Strikes
* Gender setting
* Age setting
* Removing user registration

Additionally, there could be a User management [meta-package](https://gist.github.com/mstaack/35f6e86a2920e3faf369) including all of these.

Each extension would provide hooks and should use hooks of other installed extensions, for example, strikes would hook into user list to add button for displaying all user’s strikes.

**Comment by Ralkage** [comment]
@jtojnar So a core extension (being User Management) with the option to add sub-packages?

**Comment by jtojnar** [comment]
@Ralkage I think the packages are mostly independent and could work without a core extension, but, of  course, if there is some functionality used in all of them, it can be factored out into a library.

**Comment by KyrneDev** [comment]
Everything in this package can be sufficiently disabled. If you think it's missing a toggle, let me know and I'll add it.

**Comment by jtojnar** [comment]
@issyrocks12 Do you mean this?

![image](https://cloud.githubusercontent.com/assets/705123/25015896/16b42498-207e-11e7-8185-e71cf72cf6e9.png)

I still see the gender and age things everywhere.

![image](https://cloud.githubusercontent.com/assets/705123/25015995/878d1008-207e-11e7-9b74-7b337e090e6e.png)

I do not really understand what those options in the Settings mean. Are they just controlling the fields displayed to user during registration? What happens when I disable the e-mail registration? Minimizing the scope of extensions would go a great length in making sure the extension only does the things I want it to do (that is list of users).

**Comment by KyrneDev** [comment]
Yes I do mean that, the next update as I said in your other issue will have the ability to hide that.

Also of note, there is already a dedicated user-list extension.

**Comment by jtojnar** [comment]
I used your `issyrocks12/flarum-ext-users-list` previously, but it is listed as abandoned in favour of user-management.

**Comment by KyrneDev** [comment]
Use 
composer require avatar4eg/flarum-ext-users-list

**Comment by jtojnar** [comment]
That one is not maintained any more either.

**Comment by KyrneDev** [comment]
I don't feel that this extension should be split, you are freee to fork the extension and remove what you don't want. Options will be added to disable more parts of the extension later.
